import React from 'react';
import { useNavigate } from 'react-router-dom';
import { APP_NAME, SUPPORT_EMAIL } from '../constants';

const Privacy: React.FC = () => {
    const navigate = useNavigate();

    return (
        <div className="flex h-screen w-full flex-col bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-white pb-20 overflow-y-auto font-sans">
            <div className="sticky top-0 z-10 bg-white/80 dark:bg-slate-950/80 backdrop-blur-md px-4 py-3 flex items-center gap-4 border-b border-slate-200 dark:border-slate-800 shadow-sm">
                <button onClick={() => navigate(-1)} className="p-2 -ml-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                    <span className="material-symbols-outlined">arrow_back</span>
                </button>
                <h1 className="text-lg font-bold">Privacy Policy</h1>
            </div>

            <div className="p-6 max-w-2xl mx-auto w-full space-y-8">
                {/* Non-Lending Disclaimer */}
                <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-xl p-4">
                    <div className="flex items-start gap-3">
                        <span className="material-symbols-outlined text-blue-600 dark:text-blue-400 mt-0.5">verified_user</span>
                        <div>
                            <h3 className="font-bold text-blue-800 dark:text-blue-300 text-sm">Non-Lending Entity Declaration</h3>
                            <p className="text-blue-700 dark:text-blue-400 text-xs mt-1 leading-relaxed">
                                {APP_NAME} is purely a management tool for personal record-keeping. We are <strong>NOT</strong> a lender, bank, or NBFC. We do not provide loans, process payments, or connect users with lenders. Your data remains yours.
                            </p>
                        </div>
                    </div>
                </div>

                <section className="space-y-3">
                    <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">1. Introduction</h2>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
                        {APP_NAME} ("we," "our," or "us") respects your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">2. Data Safety & Permissions</h2>

                    <div className="space-y-2">
                        <h3 className="font-bold text-base text-slate-800 dark:text-slate-200">A. Personal Ledger Data</h3>
                        <p className="text-slate-600 dark:text-slate-400 text-sm">
                            We collect basic account information (name, business ID) to manage your professional records. We <strong>DO NOT</strong> collect or upload sensitive personal data like Contacts, Call Logs, or SMS from your device.
                        </p>
                    </div>

                    <div className="space-y-2">
                        <h3 className="font-bold text-base text-slate-800 dark:text-slate-200">B. App Permissions Disclosure</h3>
                        <p className="text-slate-600 dark:text-slate-400 text-sm mb-2">
                            The following permissions are used strictly for app functionality as a record management tool:
                        </p>
                        <ul className="list-disc pl-5 space-y-3 text-slate-600 dark:text-slate-400 text-sm">
                            <li>
                                <strong>Camera (Document Management):</strong>
                                <span className="block text-xs mt-1 text-slate-500">
                                    Used only when you choose to scan physical record documents for your own private cloud storage.
                                </span>
                            </li>
                            <li>
                                <strong>Files & Storage:</strong>
                                <span className="block text-xs mt-1 text-slate-500">
                                    Required to save and export PDF ledger reports and receipts generated by the user.
                                </span>
                            </li>
                            <li>
                                <strong>Notifications:</strong>
                                <span className="block text-xs mt-1 text-slate-500">
                                    Used for ledger updates and scheduled record reminders.
                                </span>
                            </li>
                        </ul>
                    </div>
                </section>

                <section className="space-y-3">
                    <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">3. Use of Your Information</h2>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
                        Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we use information collected via the App to:
                    </p>
                    <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-600 dark:text-slate-400 text-sm">
                        <li>Create and manage your account.</li>
                        <li>Process loan records and calculate repayments.</li>
                        <li>Generate reports and receipts you request.</li>
                        <li>Notify you of updates or loan maturity.</li>
                    </ul>
                </section>

                <section className="space-y-3">
                    <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">4. Zero Data Sharing Policy</h2>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
                        We adhere to a strict <strong>Zero Data Sharing</strong> policy. We do not sell, trade, or transfer your Personally Identifiable Information to outside parties, credit bureaus, or recovery agents. Your data is stored securely on Google Firebase servers and is accessible only by you.
                    </p>
                </section>

                <section className="space-y-3">
                    <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">5. Security of Your Information</h2>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
                        We use administrative, technical, and physical security measures (including Firebase Authentication and Firestore Security Rules) to help protect your personal information.
                    </p>
                </section>

                <section className="space-y-3">
                    <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">6. Policy for Children</h2>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
                        We do not knowingly solicit information from or market to children under the age of 13.
                    </p>
                </section>

                <div className="pt-10 border-t border-slate-100 dark:border-slate-800 text-center text-xs text-slate-400">
                    <p>Contact Us: {SUPPORT_EMAIL}</p>
                    <p className="mt-1">Last updated: December 23, 2025</p>
                </div>
            </div>
        </div>
    );
};

export default Privacy;
